# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.34357276 0.83933186 0.9106926  0.42901194 0.27810175]
 [0.70710906 0.55301554 0.28371987 0.72844455 0.33440787]
 [0.21367951 0.52486993 0.10528268 0.30691726 0.71636368]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]

[[ 1.61501192  0.67638149 -1.45152933  1.22443375 -0.58017224]
 [-0.3102225   0.39205006  0.7041104  -1.551546   -0.15054843]
 [-0.95693799 -1.25349722  0.66811185 -0.97291793  1.37719293]
 [-0.72620071 -0.62131627 -0.6377851   0.40307452 -0.80265597]
 [ 0.83805556 -0.09564034 -1.11676707  0.31097421 -0.01398846]
 [-1.27707028 -1.00167669  0.41267942  0.42317926  0.43600349]
 [-1.04024216 -0.13037734 -0.26715387 -0.21315662  1.22621588]
 [-1.04543675 -1.03524176 -0.84841577  0.73263246  0.47026447]
 [-1.6920633  -0.54813675 -1.08933008 -0.05318117  0.03738953]
 [ 0.95831719 -0.17126723  0.369956    0.8755153   0.38205062]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5039616710164104
0.8368536276126699


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.07792904646827015
1.6150119237634875


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.1975699   0.38760613  0.16638171  1.2730573   0.68556591 -0.23863841
 -0.20371157  0.12541606 -0.14413704 -0.71236547 -2.00169825  1.03284608
  0.04366234  0.00506259  1.62857934  1.94779414  0.49165473  2.01997743
  0.54891949]
-0.20371156920676411


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.68556591 -0.23863841 -0.20371157  0.12541606 -0.14413704]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.1975699   1.2730573  -0.20371157 -0.71236547  0.04366234]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.34357276 0.83933186 0.9106926  0.42901194 0.27810175]
 [0.70710906 0.55301554 0.28371987 0.72844455 0.33440787]
 [0.21367951 0.52486993 0.10528268 0.30691726 0.71636368]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]
0.28371987338811777
0.28371987338811777


In [19]:
print(rand_mat[0:2,1:3])

[[0.83933186 0.9106926 ]
 [0.55301554 0.28371987]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.1975699   0.38760613  0.16638171  1.2730573   0.68556591 -0.23863841
 -0.20371157  0.12541606 -0.14413704 -0.71236547 -2.00169825  1.03284608
  0.04366234  0.00506259  1.62857934  1.94779414  0.49165473  2.01997743
  0.54891949]

[-1.1975699   0.38760613  0.16638171  4.          4.         -0.23863841
 -0.20371157  0.12541606 -0.14413704 -0.71236547 -2.00169825  1.03284608
  0.04366234  0.00506259  1.62857934  1.94779414  0.49165473  2.01997743
  0.54891949]

[-1.1975699   0.38760613  0.16638171  1.          2.         -0.23863841
 -0.20371157  0.12541606 -0.14413704 -0.71236547 -2.00169825  1.03284608
  0.04366234  0.00506259  1.62857934  1.94779414  0.49165473  2.01997743
  0.54891949]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.34357276 0.83933186 0.9106926  0.42901194 0.27810175]
 [0.70710906 0.55301554 0.28371987 0.72844455 0.33440787]
 [0.21367951 0.52486993 0.10528268 0.30691726 0.71636368]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]

[[0.34357276 0.83933186 0.9106926  0.42901194 0.27810175]
 [0.70710906 0.55301554 0.28371987 0.         0.        ]
 [0.21367951 0.52486993 0.10528268 0.         0.        ]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.34357276 0.83933186 0.9106926 ]
 [0.70710906 0.55301554 0.28371987]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.42901194 0.27810175]
 [3.         3.         3.         0.         0.        ]
 [0.21367951 0.52486993 0.10528268 0.         0.        ]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.42901194 0.27810175]
 [3.         3.         3.         0.         0.        ]
 [0.21367951 0.52486993 0.10528268 0.         0.        ]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-1.26771597 -0.55029898  0.14112416 -0.85800593 -0.35434379 -2.02477332
 -0.97748171  0.80090271  1.03652608  0.98248694 -1.34026317 -0.89831649
  0.42889636 -0.35940802 -0.15459562]
[False False  True False False False False  True  True  True False False
  True False False]
[0.14112416 0.80090271 1.03652608 0.98248694 0.42889636]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 1.61501192  0.67638149 -1.45152933  1.22443375 -0.58017224]
 [-0.3102225   0.39205006  0.7041104  -1.551546   -0.15054843]
 [-0.95693799 -1.25349722  0.66811185 -0.97291793  1.37719293]
 [-0.72620071 -0.62131627 -0.6377851   0.40307452 -0.80265597]
 [ 0.83805556 -0.09564034 -1.11676707  0.31097421 -0.01398846]
 [-1.27707028 -1.00167669  0.41267942  0.42317926  0.43600349]
 [-1.04024216 -0.13037734 -0.26715387 -0.21315662  1.22621588]
 [-1.04543675 -1.03524176 -0.84841577  0.73263246  0.47026447]
 [-1.6920633  -0.54813675 -1.08933008 -0.05318117  0.03738953]
 [ 0.95831719 -0.17126723  0.369956    0.8755153   0.38205062]]
[1.61501192 0.67638149 1.22443375 0.39205006 0.7041104  0.66811185
 1.37719293 0.40307452 0.83805556 0.31097421 0.41267942 0.42317926
 0.43600349 1.22621588 0.73263246 0.47026447 0.03738953 0.95831719
 0.369956   0.8755153  0.38205062]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-1.26771597 -0.55029898  0.14112416 -0.85800593 -0.35434379 -2.02477332
 -0.97748171  0.80090271  1.03652608  0.98248694 -1.34026317 -0.89831649
  0.42889636 -0.35940802 -0.15459562]

[-1.26771597 -0.55029898  0.14112416 -0.85800593 -0.35434379 -2.02477332
 -0.97748171 -5.         -5.         -5.         -1.34026317 -0.89831649
  0.42889636 -0.35940802 -0.15459562]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 1.61501192  0.67638149 -1.45152933  1.22443375 -0.58017224]
 [-0.3102225   0.39205006  0.7041104  -1.551546   -0.15054843]
 [-0.95693799 -1.25349722  0.66811185 -0.97291793  1.37719293]
 [-0.72620071 -0.62131627 -0.6377851   0.40307452 -0.80265597]
 [ 0.83805556 -0.09564034 -1.11676707  0.31097421 -0.01398846]
 [-1.27707028 -1.00167669  0.41267942  0.42317926  0.43600349]
 [-1.04024216 -0.13037734 -0.26715387 -0.21315662  1.22621588]
 [-1.04543675 -1.03524176 -0.84841577  0.73263246  0.47026447]
 [-1.6920633  -0.54813675 -1.08933008 -0.05318117  0.03738953]
 [ 0.95831719 -0.17126723  0.369956    0.8755153   0.38205062]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.42901194 0.27810175]
 [3.         3.         3.         0.         0.        ]
 [0.21367951 0.52486993 0.10528268 0.         0.        ]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]

[[ 1.61501192  0.67638149 -1.45152933  1.22443375 -0.58017224]
 [-0.3102225   0.39205006  0.7041104  -1.551546   -0.15054843]
 [-0.95693799 -1.25349722  0.66811185 -0.97291793  1.37719293]
 [-0.72620071 -0.62131627 -0.6377851   0.40307452 -0.80265597]
 [ 0.83805556 -0.09564034 -1.11676707  0.31097421 -0.01398846]
 [-1.27707028 -1.00167669  0.41267942  0.42317926  0.43600349]
 [-1.04024216 -0.13037734 -0.26715387 -0.21315662  1.22621588]
 [-1.04543675 -1.03524176 -0.84841577  0.73263246  0.47026447]
 [-1.6920633  -0.54813675 -1.08933008 -0.05318117  0.03738953]
 [ 0.95831719 -0.17126723  0.369956    0.8755153   0.38205062]]
[[3.         3.         3.         0.42901194 0.27810175]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.42901194 0.27810175]
 [3.         3.         3.         0.         0.        ]
 [0.21367951 0.52486993 0.10528268 0.         0.        ]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]

[[3.         3.         3.         0.42901194 0.27810175]
 [3.         3.         3.         0.         0.        ]
 [0.21367951 0.52486993 0.10528268 0.         0.        ]
 [0.73892623 0.98073441 0.36619365 0.07792905 0.94788418]
 [0.7907561  0.12711957 0.58960828 0.13857705 0.56679238]]
